### ISSUE TITLE
PyPy support?

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/mgp2pdf#7]
```
$ tox -e pypy
GLOB sdist-make: /home/mg/src/mgp2pdf/setup.py
pypy create: /home/mg/src/mgp2pdf/.tox/pypy
pypy installdeps: mock
pypy inst: /home/mg/src/mgp2pdf/.tox/dist/mgp2pdf-0.10.1.dev0.zip
pypy installed: cffi==0.8.6,funcsigs==0.4,greenlet==0.4.5,mgp2pdf==0.10.1.dev0,mock==1.3.0,pbr==1.8.0,Pillow==2.9.0,readline==6.2.4.1,reportlab==3.2.0,six==1.9.0,wheel==0.24.0
pypy runtests: PYTHONHASHSEED='2316777835'
pypy runtests: commands[0] | python tests.py
....E.................................
======================================================================
ERROR: test_conversion (__main__.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 53, in test_conversion
    p.makePDF(pdf)
  File "/home/mg/src/mgp2pdf/mgp2pdf.py", line 1057, in makePDF
    s.drawOn(canvas, self.pageSize)
  File "/home/mg/src/mgp2pdf/mgp2pdf.py", line 261, in drawOn
    self.wordWrap(canvas, w, h)
  File "/home/mg/src/mgp2pdf/mgp2pdf.py", line 244, in wordWrap
    new_lines += line.split(canvas, w, h)
  File "/home/mg/src/mgp2pdf/mgp2pdf.py", line 362, in split
    cw, ch = chunk.size(canvas, w, h)
  File "/home/mg/src/mgp2pdf/mgp2pdf.py", line 555, in size
    textwidth += canvas.stringWidth(run, self.font, fontSize)
  File "/home/mg/src/mgp2pdf/.tox/pypy/site-packages/reportlab/pdfgen/canvas.py", line 1644, in stringWidth
    (fontSize,self._fontsize)[fontSize is None])
  File "/home/mg/src/mgp2pdf/.tox/pypy/site-packages/reportlab/pdfbase/pdfmetrics.py", line 707, in stringWidth
    return getFont(fontName).stringWidth(text, fontSize, encoding=encoding)
  File "/home/mg/src/mgp2pdf/.tox/pypy/site-packages/reportlab/pdfbase/pdfmetrics.py", line 358, in stringWidth
    return instanceStringWidthT1(self, text, size, encoding=encoding)
SystemError: Bad internal call!

----------------------------------------------------------------------
Ran 38 tests in 0.837s

FAILED (errors=1)
ERROR: InvocationError: '/home/mg/src/mgp2pdf/.tox/pypy/bin/python tests.py'
----------------------------------------------------------------------
_________________________________ summary _________________________________
ERROR:   pypy: commands failed

```

**Comment by mgedmin** [comment]
```
$ pypy --version
Python 2.7.8 (2.5.0+dfsg-2, Feb 12 2015, 05:23:41)
[PyPy 2.5.0 with GCC 4.9.2]
```

**Comment by mgedmin** [comment]
Works fine with
```
Python 2.7.9 (2.6.0+dfsg-3, Jul 04 2015, 05:43:17)
[PyPy 2.6.0 with GCC 4.9.3]
```

**Comment by mgedmin** [comment]
Welp, Travis has pypy 2.5.0, which doesn't like reportlab.

See https://github.com/travis-ci/travis-ci/issues/4756

**Comment by mgedmin** [comment]
Travis + pypy 4.0.0 = [segfaults](https://travis-ci.org/mgedmin/mgp2pdf/builds/91417375) I cannot reproduce on my laptop.
